import React from 'react'
class Privacy_Policy extends React.Component{
    render(){
        return(
            <div style={{width:'95%',margin:'0 auto'}}>
            <p ><span >&#xa0;</span></p>
            <h2 style={{textAlign:'center'}}><span >Privacy Policy</span></h2>
            <p ><span >&#xa0;</span></p>
            <p ><span >This Privacy Policy
                            explains
                            how data about you is collected, used and disclosed by DECENTRALIZED CYBERSPACE
                            FOUNDATION LIMITED
                            ("we" or "us").</span></p>
            <p ><span >This Privacy Policy
                            (together
                            with our Terms of Service and any other documents referred to therein or herein) applies
                            to information
                            we collect when you use our websites, mobile applications, APIs, Violas wallet services
                            and other online
                            products and services (collectively, the "Services") or when you otherwise interact with
                            us.</span>
            </p>
            <p ><span >We may change this
                            Privacy
                            Policy from time to time. If we make changes, we will notify you by revising the date at
                            the bottom of
                            the policy and, optionally, we may provide you with additional notice such as by adding
                            a statement to
                            on our blog, twitter or by sending you an email notification. We encourage you to review
                            the Privacy
                            Policy whenever you access the Services to stay up to date about our information
                            practices and the ways
                            you can help secure your privacy.</span></p>
            <p ><span >&#xa0;</span></p>
            <h4 ><span >Wallet
                            Information:</span></h4>
            <p ><span >When you install
                            Violas wallet
                            through our download service, your private key is automatically generated by the
                            downloaded wallet and
                            stored in your wallet on your device only. All your private keys will never leave your
                            wallet on your
                            device.</span></p>
            <p ><span >&#xa0;</span></p>
            <h4 ><span >Information we are
                            given</span></h4>
            <p ><span >We log information you
                            provide
                            directly to us. For instance, we log information when you participate with any feature
                            of the Services,
                            complete a form, initiate a Violas, Libra or Bitcoin transaction via the Services,
                            request customer
                            support or otherwise communicate with us.</span></p>
            <p ><span >The types of
                            information we
                            may collect include your Violas, Libra and Bitcoin addresses, alias, mobile and any
                            other information
                            you choose to provide.</span></p>
            <p ><span >&#xa0;</span></p>
            <h4 ><span >When you access or
                            use our
                            Services, we log information about you, including:</span></h4>
            <h4 ><span >Web Page
                            Information:</span>
            </h4>
            <p ><span >We may log information
                            about
                            your use of the Services, including the version of the software browser you use, access
                            times, pages
                            viewed, your IP address and the page you visited before navigating to our
                            websites.</span></p>
            <h4 ><span >Device
                            Information:</span></h4>
            <p ><span >We may collect
                            information
                            about the mobile device you use to access our mobile application, including the hardware
                            model,
                            operating system and version, unique device identifiers and mobile network
                            information.</span></p>
            <h4 ><span >Information Collected
                            by Other
                            Tracking Technologies:</span></h4>
            <p ><span >We use various
                            technologies to
                            collect information, and this may include which areas and features of our Services are
                            popular and count
                            visits. </span></p>
            <p ><span >&#xa0;</span></p>
            <h4 ><span >We may use
                            information about
                            you for various purposes, including to:</span></h4>
            <p ><span >Provide, maintain and
                            improve
                            our Services</span></p>
            <p ><span >Provide and deliver
                            the
                            services you request, facilitate Violas, Libra and Bitcoin transactions and send you
                            related
                            information, including confirmations</span></p>
            <p ><span >Send you technical
                            notices,
                            updates, security alerts, and support and administrative messages</span></p>
            <p ><span >Respond to your
                            comments,
                            questions and requests and provide customer service</span></p>
            <p ><span >Communicate with you
                            about
                            products, services, offers, promotions, rewards, and events offered by us</span></p>
            <p ><span >Monitor and analyze
                            trends,
                            usage and activities in connection with our Services in an aggregate and anonymous
                            manner</span></p>
            <p ><span >Process and deliver
                            contest
                            entries and rewards</span></p>
            <p ><span >Link or combine with
                            information we get from others to help understand your needs and provide you with better
                            service</span>
            </p>
            <p ><span >Carry out any other
                            purpose
                            for which you provided the information.</span></p>
            <p ><span >&#xa0;</span></p>
            <h4 ><span >We may share
                            information about
                            you as follows or as otherwise described in this Privacy Policy:</span></h4>
            <p ><span >With the Violas
                            Network, we
                            will share your public wallet address and any transaction details to facilitate any
                            transaction request
                            you submit via the Services</span></p>
            <p ><span >With vendors,
                            consultants and
                            other service providers who need access to such information to carry out work on our
                            behalf; it is our
                            practice to require such parties to handle the information in a manner consistent with
                            our
                            policies</span></p>
            <p ><span >In response to a
                            request for
                            information if we believe disclosure is in accordance with, or as otherwise required by,
                            any applicable
                            law, regulation or legal process</span></p>
            <p ><span >If we believe your
                            actions are
                            inconsistent with the spirit or language of our user agreements or policies, or to
                            protect the rights,
                            property and safety of us or others</span></p>
            <p ><span >In connection with, or
                            during
                            negotiations of, any merger, sale of our assets, financing or acquisition of all or a
                            portion of our
                            business to another company</span></p>
            <p ><span >With your consent or
                            at your
                            direction, including if we notify you through our Services that the information you
                            provide will be
                            shared in a particular manner and you provide such information</span></p>
            <p ><span >&#xa0;</span></p>
            <p ><span >&#xa0;</span></p>
            <p ><span >Last Updated: Friday,
                            November
                            22 2019</span></p>
            <p ><span >&#xa0;</span></p>
            <p ><span >Copyright 2019 Violas
                            | About
                            us</span></p>
            <p ><span >DECENTRALIZED
                            CYBERSPACE
                            FOUNDATION LIMITED</span></p>
            <p ><span >38 TOH TUCK ROAD
                            #05-02</span>
            </p>
            <p ><span >GOODLUCK GARDEN</span>
            </p>
            <p ><span >SINGAPORE
                            (596716)</span></p>
            <p ><span >&#xa0;</span></p>
    </div>
        )
    }
}
export default Privacy_Policy;